import type { Metadata } from 'next'
import { Inter, Poppins, Roboto_Mono, Agbalumo, Kenia } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: "--inter" });
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ["100", "400", "500", "600"]
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
})
const agbalumo = Agbalumo({
  subsets: ["latin"],
  variable: "--agbalumo",
  weight: ["400"],
});
const kenia = Kenia({
  subsets: ["latin"],
  variable: "--kenia",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={` ${inter.variable} ${poppins.variable} ${robotoMono.variable} ${agbalumo.variable} ${kenia.variable}`}>
      <body>{children}</body>
    </html>
  )
}
